### ISSUE TITLE
Hmmcleaner

### ISSUE THREAD

**Issue by yuzhenpeng** [sjswuitchik/duck_comp_gen#1]
Hi, 
would you mind share the hmmcleaner_0.180750.sif. I can not install it in my computer.

Thank you.

**Comment by sjswuitchik** [comment]
Hello,

HmmCleaner is a perl application that we containerized on our cluster because there were some install/dependency issues. It's not available as hmmcleaner_0.180750.sif outside of our cluster, but you can download via cpan: https://metacpan.org/dist/Bio-MUST-Apps-HmmCleaner/view/bin/HmmCleaner.pl
